site_name: pynotify-auto
site_description: Zero-Code automatic notifications for long-running Python scripts.
site_url: https://shahbhuwan.github.io/pynotify-auto/
repo_url: https://github.com/shahbhuwan/pynotify-auto
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.smartsymbols
